language: nodejs
nodejs:
- '6'
install:
- npm i -g typings
- typings i
- npm i
script:
- npm run build
deploy:
  provider: npm
  email: zachbray@googlemail.com
  api_key: $NPM_KEY
  on:
    tags: true
