language: nodejs
nodejs:
- 'stable'
before_install:
- npm i -g typings
- typings i
script:
- npm run build
deploy:
  provider: npm
  email: zachbray@googlemail.com
  api_key: $NPM_KEY
  on:
    tags: true
